apiVersion: v1
kind: Pod
metadata:
  name: ms1
spec:
  containers:
    - name: microservice1
      image: nourbenali/visionaryops-microservice11:final
      ports:
        - containerPort: 9989
      env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/basepfe3"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin"
        - name: KAFKA_URL
          value: "kafka-service:9092"
        - name: PORT
          value: "9989"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo-service:4317"
        - name: OTEL_EXPORTER_OTLP_TIMEOUT
          value: "3000"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
  volumes:
    - name: postgres-data
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: microservice1-service
spec:
  type: NodePort
  selector:
    app: microservice1
  ports:
    - protocol: TCP
      port: 9989
      targetPort: 9989
      nodePort: 30100